controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gimbal_yaw_controller:
      type: joint_trajectory_controller/JointTrajectoryController

gimbal_yaw_controller:
  ros__parameters:
    joints:
      - gimbal_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
